"""
Dedicated logger for email-related activities
Author: Ben Walker (BenRWalker@icloud.com)
"""

from logger_config import setup_logger
from functools import wraps
import asyncio

email_logger = setup_logger('email_activity', use_json=False)


def log_email_operation(operation_name: str):
    def decorator(func):
        @wraps(func)
        async def async_wrapper(*args, **kwargs):
            email_logger.info(f"{'='*60}")
            email_logger.info(f"Starting: {operation_name}")
            email_logger.info(f"{'='*60}")
            
            if args:
                email_logger.debug(f"Arguments: {args[:2]}...")
            if kwargs:
                email_logger.debug(f"Keyword arguments: {list(kwargs.keys())}")
            
            try:
                result = await func(*args, **kwargs)
                email_logger.info(f"✓ {operation_name} completed successfully")
                
                if hasattr(result, '__len__') and not isinstance(result, str):
                    email_logger.debug(f"Result length: {len(result)}")
                
                return result
                
            except Exception as e:
                email_logger.error(f"✗ {operation_name} failed: {e}", exc_info=True)
                raise
            finally:
                email_logger.info(f"{'='*60}")
                email_logger.info(f"Finished: {operation_name}")
                email_logger.info(f"{'='*60}\n")
        
        @wraps(func)
        def sync_wrapper(*args, **kwargs):
            email_logger.info(f"{'='*60}")
            email_logger.info(f"Starting: {operation_name}")
            email_logger.info(f"{'='*60}")
            
            if args:
                email_logger.debug(f"Arguments: {args[:2]}...")
            if kwargs:
                email_logger.debug(f"Keyword arguments: {list(kwargs.keys())}")
            
            try:
                result = func(*args, **kwargs)
                email_logger.info(f"✓ {operation_name} completed successfully")
                
                if hasattr(result, '__len__') and not isinstance(result, str):
                    email_logger.debug(f"Result length: {len(result)}")
                
                return result
                
            except Exception as e:
                email_logger.error(f"✗ {operation_name} failed: {e}", exc_info=True)
                raise
            finally:
                email_logger.info(f"{'='*60}")
                email_logger.info(f"Finished: {operation_name}")
                email_logger.info(f"{'='*60}\n")
        
        if asyncio.iscoroutinefunction(func):
            return async_wrapper
        else:
            return sync_wrapper
    
    return decorator


def log_agent_invocation(agent_name: str, message_preview: str):

    email_logger.info(f"Agent Invoked: {agent_name}")
    email_logger.info(f"   Prompt preview: {message_preview[:100]}...")


def log_email_generation(agent_name: str, email_preview: str):
    email_logger.info(f"Email Generated by: {agent_name}")
    email_logger.info(f"   Email preview: {email_preview[:150]}...")
    email_logger.debug(f"   Full email length: {len(email_preview)} characters")


def log_email_send(recipient: str, subject: str, status: str):
    icon = "✅" if status == "success" else "❌"
    email_logger.info(f"{icon} Email Send: {recipient}")
    email_logger.info(f"   Subject: {subject}")
    email_logger.info(f"   Status: {status}")


def log_bulk_send_summary(total: int, successful: int, failed: int):
    email_logger.info(f"Bulk Send Summary:")
    email_logger.info(f"   Total: {total}")
    email_logger.info(f"   ✅ Successful: {successful}")
    email_logger.info(f"   ❌ Failed: {failed}")
    email_logger.info(f"   Success Rate: {(successful/total)*100:.1f}%")
